jobs:
  - job: MAIN
    timeoutInMinutes: 60
    pool:
      vmImage: vs2017-win2016
    steps:
      - script: git clone https://github.com/lazka/msys2-ci-base.git %CD:~0,2%\msys64
        displayName: Install MSYS2
      - script: |
          set PATH=%CD:~0,2%\msys64\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\msys64\usr\bin\pacman --noconfirm -Syyuu
        displayName: Update MSYS2
      - script: |
          set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\msys64\usr\bin\bash -lc ".azure/msys2-install.sh"
        displayName: Install Depdendencies
        env:
          MSYS2_ARCH: i686
          MSYSTEM: MINGW32
          CHERE_INVOKING: yes
      - script: |
          set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\msys64\usr\bin\bash -lc ".azure/msys2-test.sh"
        displayName: Run Tests
        env:
          MSYS2_ARCH: i686
          MSYSTEM: MINGW32
          CHERE_INVOKING: yes
      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '**/test-*.xml'
          testRunTitle: 'Publish test results'
